"""empty message

Revision ID: 2a667b6e3df3
Revises: 712fec4b34b0
Create Date: 2019-03-08 14:28:15.974772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a667b6e3df3'
down_revision = '712fec4b34b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', sa.String(length=16), nullable=True))
    op.add_column('resource', sa.Column('is_embed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'is_embed')
    op.drop_column('project', 'status')
    # ### end Alembic commands ###
