"""empty message

Revision ID: 37a8cc7186ff
Revises: 3ec65867f875
Create Date: 2019-04-03 15:53:05.948425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a8cc7186ff'
down_revision = '3ec65867f875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('fmt', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'fmt')
    # ### end Alembic commands ###
