"""empty message

Revision ID: 3ec65867f875
Revises: 0524918b6a8c
Create Date: 2019-04-03 15:34:31.299056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec65867f875'
down_revision = '0524918b6a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=True),
    sa.Column('title', sa.Unicode(length=256), nullable=True),
    sa.Column('path', sa.Unicode(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('title')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=256), nullable=True),
    sa.Column('path', sa.Unicode(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('sources_renderings',
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('rendering_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rendering_id'], ['rendering.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], )
    )
    op.add_column('project', sa.Column('license_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'license', ['license_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'license_id')
    op.drop_table('sources_renderings')
    op.drop_table('source')
    op.drop_table('license')
    # ### end Alembic commands ###
