"""empty message

Revision ID: c59f1ce5a3dc
Revises: 2a667b6e3df3
Create Date: 2019-03-21 17:14:31.730928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59f1ce5a3dc'
down_revision = '2a667b6e3df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('category', sa.String(length=32), nullable=True))
    op.drop_column('project', 'status')
    op.add_column('resource', sa.Column('doc_url', sa.Unicode(length=256), nullable=True))
    op.add_column('resource', sa.Column('license', sa.Unicode(length=64), nullable=True))
    op.add_column('resource', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('resource', sa.Column('pipeline', sa.UnicodeText(), nullable=True))
    op.drop_column('resource', 'is_embed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('is_embed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('resource', 'pipeline')
    op.drop_column('resource', 'order')
    op.drop_column('resource', 'license')
    op.drop_column('resource', 'doc_url')
    op.add_column('project', sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.drop_column('project', 'category')
    # ### end Alembic commands ###
