"""empty message

Revision ID: e8f14ef94128
Revises: aeb8bd988709
Create Date: 2018-08-20 12:27:52.520960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f14ef94128'
down_revision = 'aeb8bd988709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('screenshot', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'screenshot')
    # ### end Alembic commands ###
