"""empty message

Revision ID: 963df45b98ee
Revises: e5e40a862da0
Create Date: 2018-07-11 15:29:03.341642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '963df45b98ee'
down_revision = 'e5e40a862da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.add_column('project', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('token_edit', sa.String(length=64), nullable=True))
    op.drop_column('resource', 'dataformat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('dataformat', postgresql.ENUM('png', 'jpg', 'geojson', 'datapackage', 'embed', name='dataformats'), autoincrement=False, nullable=True))
    op.drop_column('project', 'token_edit')
    op.drop_column('project', 'is_hidden')
    op.drop_column('project', 'is_featured')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
