"""empty message

Revision ID: a4d289b9abd3
Revises: 16080f1821df
Create Date: 2019-04-10 18:43:26.107145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d289b9abd3'
down_revision = '16080f1821df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('license', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('license', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('organisation', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('project', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('rendering', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('source', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('source', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('rendering', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('project', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('organisation', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('license', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('license', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
