"""empty message

Revision ID: dbcd7d8df928
Revises: e8f14ef94128
Create Date: 2018-08-30 15:02:24.309423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcd7d8df928'
down_revision = 'e8f14ef94128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('notes', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'notes')
    # ### end Alembic commands ###
