"""empty message

Revision ID: e5e40a862da0
Revises: 
Create Date: 2018-07-11 10:01:22.679345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e40a862da0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.drop_index('idx_resource_features', table_name='resource')
    op.drop_column('resource', 'features')
    op.add_column('user', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'organisation', ['organisation_id'], ['id'])
    op.drop_column('user', 'logo')
    op.drop_column('user', 'organisation')
    op.drop_column('user', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('organisation', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('logo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'organisation_id')
    op.add_column('resource', sa.Column('features', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON'), autoincrement=False, nullable=True))
    op.create_index('idx_resource_features', 'resource', ['features'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
